[package]
name = "rust-upload-reflector"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unit-wasm = { path = "../../../src/rust", version = "0.2.0" }

[lib]
crate-type = ["cdylib"]
